using System;
using System.Text;

namespace SWallTech
{
	/* C# Bean representing the following Table:
        Library  : CAMRALIB
        Table    : CAFPMHIM
        Created  : 5/14/2007 3:47:11 PM
        Generator: Stonewall Technologies BeanMaker 0.0.1

	This class extends the Abstract base class SWallTech.REMhim_Base
	By placing any customization code in this file, you can regenerate the Base class
	to reflect any database changes without losing your custom code.

	Customization Record:
	DATE			ACTION
        5/14/2007 3:47:11 PM		Generated by: Stonewall Technologies BeanMaker 0.0.1

    */

	public class REMhim : REMhim_Base
	{
		#region Variables

		#endregion Variables

		#region Constructors

		private REMhim() : base()
		{
		}

		public REMhim(IDBAccess db) : base(db)
		{
			this.db = db;
		}

		public REMhim(IDBAccess db, FixedDecimal IRECNO, FixedDecimal IDWELL, FixedDecimal ISEQNO) : base(db, IRECNO, IDWELL, ISEQNO)
		{
		}

		#endregion Constructors

		#region Properties

		#endregion Properties

		#region Public Static Methods

		#endregion Public Static Methods

		#region Public Methods

		#endregion Public Methods

		#region Private Methods

		#endregion Private Methods
	}
}