using System;
using System.Text;

namespace SWallTech
{
	/* C# Bean representing the following Table:
        Library  : CAMRALIB
        Table    : CAFPMOBH
        Created  : 5/14/2007 3:41:57 PM
        Generator: Stonewall Technologies BeanMaker 0.0.1

	This class extends the Abstract base class SWallTech.REMobh_Base
	By placing any customization code in this file, you can regenerate the Base class
	to reflect any database changes without losing your custom code.

	Customization Record:
	DATE			ACTION
        5/14/2007 3:41:57 PM		Generated by: Stonewall Technologies BeanMaker 0.0.1

    */

	public class REMobh : REMobh_Base
	{
		#region Variables

		#endregion Variables

		#region Constructors

		private REMobh() : base()
		{
		}

		public REMobh(IDBAccess db) : base(db)
		{
			this.db = db;
		}

		public REMobh(IDBAccess db, FixedDecimal HRECNO) : base(db, HRECNO)
		{
		}

		#endregion Constructors

		#region Properties

		#endregion Properties

		#region Public Static Methods

		#endregion Public Static Methods

		#region Public Methods

		#endregion Public Methods

		#region Private Methods

		#endregion Private Methods
	}
}